import { readFile } from 'node:fs/promises';

const files = {
  app: await readFile(new URL('../public/assets/live-app.js', import.meta.url), 'utf8'),
  client: await readFile(new URL('../public/assets/api-client.js', import.meta.url), 'utf8'),
  css: await readFile(new URL('../public/assets/styles.css', import.meta.url), 'utf8'),
  sw: await readFile(new URL('../public/sw.js', import.meta.url), 'utf8'),
  worker: await readFile(new URL('../worker/index.mjs', import.meta.url), 'utf8'),
  html: await readFile(new URL('../public/index.html', import.meta.url), 'utf8'),
  migration: await readFile(new URL('../migrations/0002_admin_roles.sql', import.meta.url), 'utf8'),
  recoveryMigration: await readFile(new URL('../migrations/0007_member_account_recovery.sql', import.meta.url), 'utf8'),
  moderationMigration: await readFile(new URL('../migrations/0008_challenge_moderation.sql', import.meta.url), 'utf8'),
  pushMigration: await readFile(new URL('../migrations/0009_push_and_deputy_review.sql', import.meta.url), 'utf8'),
  singleCandidateMigration: await readFile(new URL('../migrations/0016_enforce_single_active_candidate.sql', import.meta.url), 'utf8'),
  wrangler: await readFile(new URL('../wrangler.jsonc', import.meta.url), 'utf8'),
};

const checks = [
  ['공개 프로필 동작', files.app.includes("view-public-profile") && files.app.includes('openPublicProfile')],
  ['TRUST 상세 동작', files.app.includes("view-trust-history") && files.app.includes('openTrustHistory')],
  ['알림 읽음 API', files.worker.includes('/notifications\\/([^/]+)\\/read') && files.client.includes('markNotificationRead')],
  ['선택형 PWA 푸시 설정', files.worker.includes('savePushSubscription') && files.worker.includes('PUSH_NOT_CONFIGURED') && files.worker.includes('sendPushNotification') && files.worker.includes('deliverWebPush') && files.worker.includes("'Content-Encoding': 'aes128gcm'") && files.client.includes('pushSettings') && files.app.includes('enablePushNotifications') && files.sw.includes("addEventListener('push'") && files.pushMigration.includes('push_subscriptions')],
  ['최고관리자 공지 푸시 발송', files.worker.includes('/api/admin/push-announcements') && files.worker.includes('sendAdminPushAnnouncement') && files.worker.includes('requirePrimaryAdmin(request, env)') && files.worker.includes('PUSH_CONFIRMATION_REQUIRED') && files.worker.includes('ADMIN_PUSH_NOT_SUBSCRIBED') && files.worker.includes('push_announcement_logs') && files.client.includes('sendPushAnnouncement') && files.app.includes('open-push-announcement') && files.app.includes('push-announcement-form')],
  ['부관리자 검토 요청 분리', files.worker.includes('addModerationNote') && files.worker.includes('requireAdmin(request, env)') && files.worker.includes('requirePrimaryAdmin(request, env)') && files.client.includes('addModerationNote') && files.app.includes('부관리자 검토 의견') && files.pushMigration.includes('moderation_review_notes')],
  ['비밀번호 변경 보안', files.worker.includes('/api/auth/change-password') && files.worker.includes('otherSessionsSignedOut') && files.client.includes('changePassword') && files.app.includes('change-password-form') && files.app.includes('submitPasswordChange')],
  ['회원 아이디·비밀번호 복구', files.worker.includes('/api/auth/find-email') && files.worker.includes('/api/auth/request-password-reset') && files.worker.includes('/api/auth/reset-password') && files.worker.includes('issuePasswordReset') && files.client.includes('findEmail') && files.client.includes('resetPassword') && files.app.includes('openEmailFinder') && files.app.includes('renderPasswordReset') && files.recoveryMigration.includes('password_resets')],
  ['소셜 로그인 모바일 복귀', files.worker.includes('oauthCompletionPage') && files.worker.includes('Safari can reject a redirect response') && files.app.includes("oauth-login")],
  ['취소 완료 화면 유지', files.app.includes('navigate(\'dashboard\')') && files.app.includes('renderModalRequestError') && files.app.includes('retry-challenge-detail')],
  ['간편 미션 자동작성', files.app.includes('renderEasyCreateWizard') && files.app.includes('generateChallengeDraft') && files.app.includes('wizardPurpose') && files.css.includes('.create-mode-switch')],
  ['TEASER 자동 양식 작성', files.app.includes('fill-teaser-template') && files.app.includes('자동 양식 채우기') && files.app.includes('실제 경험·수행 방법에 맞게 내용을 수정하세요.')],
  ['성공·증빙 체크형 작성', files.app.includes('renderCriteriaCheckBuilder') && files.app.includes('updateCriteriaFromChecks') && files.app.includes('successCheck') && files.app.includes('evidenceCheck') && files.css.includes('.criteria-option-grid')],
  ['보상금 용어 한글화', files.app.includes('보상금 준비 시점') && !files.app.includes('<label>Funding Trigger')],
  ['메인 LIVE 시각효과', files.app.includes('live-pill"><i>') && files.css.includes('@keyframes liveDotBlink') && files.css.includes('prefers-reduced-motion')],
  ['LIVE 보상금순 자동교체', files.app.includes('hydrateLiveChallengeRotation') && files.app.includes("sortChallenges(state.challenges.filter") && files.app.includes("'reward'") && files.app.includes('data-live-challenge') && files.app.includes('modu-live-rank-index') && !files.app.includes("board.matches(':hover')")],
  ['LIVE 카드 이동·입력 정렬', files.css.includes('heroBoardFloat 20s') && files.css.includes('calc(-100vw + 720px)') && files.css.includes('background: transparent') && files.css.includes('.hero-board:hover') && files.app.includes('reward-schedule-grid') && files.css.includes('.reward-schedule-grid')],
  ['관리자 운영 목록', files.worker.includes('pendingSettlements') && files.app.includes('admin-ops-grid')],
  ['미션 사전검토·승인·비공개 보관', files.worker.includes('analyzeChallengeForModeration') && files.worker.includes('CHALLENGE_MODERATION_PENDING') && files.worker.includes('approveModerationChallenge') && files.worker.includes('archiveModerationChallenge') && files.worker.includes('CHALLENGE_MODERATION_ARCHIVE') && files.worker.includes('requirePrimaryAdmin(request, env)') && files.client.includes('approveModerationChallenge') && files.client.includes('archiveModerationChallenge') && files.app.includes('관리자 검토 대기') && files.app.includes('비공개 보관') && files.moderationMigration.includes('moderation_reasons_json')],
  ['최고관리자 회원 상세 조회', files.worker.includes('api\\/admin\\/members') && files.worker.includes('getAdminMemberDetail') && files.worker.includes('ADMIN_MEMBER_DETAIL_VIEW') && files.worker.includes('requirePrimaryAdmin(request, env)') && files.client.includes('adminMemberDetail') && files.app.includes('view-admin-member') && files.app.includes('openAdminMemberDetail')],
  ['확장 가입·인증·소셜 로그인', files.worker.includes('emailVerificationEnabled') && files.worker.includes('issueEmailVerification') && files.worker.includes('fetchOAuthProfile') && files.worker.includes('GOOGLE_OAUTH_CLIENT_ID') && files.worker.includes('NAVER_OAUTH_CLIENT_ID') && files.worker.includes('oauth_signup_pending') && files.client.includes('verifyEmail') && files.app.includes('challengeIntent') && files.app.includes('oauth-login')],
  ['필수 가입정보 검증', files.app.includes('confirmPassword') && files.app.includes('data-birth-year-digit') && files.app.includes('signup-demographic-grid') && files.app.includes('<option>전국</option>') && files.app.includes('value="female"') && files.app.includes('value="male"') && !files.app.includes('value="prefer_not"') && files.worker.includes("new Set(['female', 'male'])") && files.worker.includes('INVALID_BIRTH_YEAR') && files.worker.includes('INVALID_GENDER')],
  ['가입 전체 동의 동작', files.app.includes('data-signup-consent-all') && files.app.includes('data-signup-consent-item') && files.app.includes('all.indeterminate') && files.css.includes('.signup-consent') && files.css.includes('.consent-all')],
  ['최고·부관리자 권한 분리', files.worker.includes('PRIMARY_ADMIN_EMAIL') && files.worker.includes('admin_roles') && files.worker.includes('requirePrimaryAdmin') && files.worker.includes('appointDeputy') && files.worker.includes("CREATE INDEX IF NOT EXISTS idx_admin_roles_role") && !files.worker.includes('await env.DB.exec(`') && files.client.includes('appointDeputy') && files.app.includes('renderDeputyAdmin') && files.migration.includes("admin_roles") && files.wrangler.includes('kpa100plus@gmail.com')],
  ['최고관리자 공개 표시명', files.worker.includes("'SUPER ADMIN'") && !files.worker.includes("'juyoungkim'") && files.app.includes('display_name')],
  ['이용방법·신뢰안전 경로', files.app.includes("state.route === 'how'") && files.app.includes("state.route === 'trust'") && files.app.includes('function renderHow()') && files.app.includes('function renderTrustSafety()')],
  ['모바일 PWA 이용안내 메뉴', files.html.includes('class="mobile-guide-nav"') && files.html.includes('data-route="how"') && files.html.includes('data-route="trust"') && files.css.includes('.mobile-guide-nav')],
  ['간편 예시 입력 범위 분리', files.app.includes('selectCreateExample') && files.app.includes("form.elements.wizardSubject.value") && !files.app.includes('data-action="generate-challenge-draft" data-example=')],
  ['가입 중복 오류 필드 표시', files.worker.includes('PHONE_EXISTS') && files.worker.includes('DISPLAY_NAME_EXISTS') && files.app.includes('showSignupFieldError') && files.css.includes('.field-error')],
  ['소셜 계정 신규 가입', files.app.includes('openSocialSignup') && files.worker.includes('oauthSignup') && files.client.includes('oauthSignup')],
  ['참여 전 미션 수정', files.worker.includes('updateChallenge') && files.worker.includes('CHALLENGE_EDIT_LOCKED') && files.client.includes('updateChallenge') && files.app.includes('challenge-edit-form')],
  ['TEASER 수정·철회', files.worker.includes('updateTeaser') && files.worker.includes('withdrawTeaser') && files.worker.includes('TEASER_WITHDRAWN') && files.client.includes('updateTeaser') && files.client.includes('withdrawTeaser') && files.app.includes('teaser-edit-form') && files.app.includes('teaser-withdraw-form')],
  ['모달 입력 임시보존', files.app.includes('saveTransientModalDraft') && files.app.includes('restoreTransientModalDraft') && files.app.includes('modu-transient-')],
  ['한글 폰트 우선순위', files.css.includes('"Malgun Gothic", "맑은 고딕"')],
  ['과도한 폰트 굵기 제거', !/font-weight:\s*(800|900)/.test(files.css)],
  ['푸터 대표자 확정 문구', files.html.includes('모두의 챌린지 대표이사: 최인란')],
  ['공유 대표이미지', files.html.includes('property="og:image"') && files.html.includes('modu-share-preview.jpg') && files.html.includes('summary_large_image')],
  ['모바일 화면 잘림 방지', files.css.includes('overflow-x: clip') && files.css.includes('100dvh') && files.css.includes('body.modal-open')],
  ['모바일 입력 이탈 방지', files.app.includes('modalScrollY') && files.app.includes('field-counter') && files.app.includes('작성 기준')],
  ['모바일 검색창·활동카드 가독성', files.app.includes('class="search-icon"') && files.app.includes('사람·업체·정보 등을 검색하세요') && files.app.includes('--activity-color:${category.color}') && files.css.includes('.search-box .search-icon') && files.css.includes('.activity-icon svg')],
  ['미션 카드 5종 디자인', ['ice', 'rose', 'graphite', 'ocean', 'sand'].every((theme) => files.app.includes(`card-theme-${theme}`) || files.css.includes(`.card-theme-${theme}`)) && files.app.includes('CARD_THEME_BY_CATEGORY') && files.app.includes('data-card-theme=') && files.css.includes('.challenge-card:focus-visible')],
  ['내 클리어 버튼·자동갱신', files.css.includes('.page-hero .btn-outline') && files.app.includes('setInterval(refreshDashboardActivity, 8000)') && files.app.includes("action === 'view-progress'")],
  ['단일 수행자 후보', files.worker.includes("WHEN status = 'SHORTLISTED' THEN 'VIEWED'") && files.worker.includes('singleCandidate: true') && files.app.includes('수행자 후보는 한 번에 1명만 선택됩니다') && files.singleCandidateMigration.includes("status = 'VIEWED'") && files.singleCandidateMigration.includes('teaserRowsPreserved')],
  ['검토기준·세무 안내', files.worker.includes('HIGH_REWARD_REVIEW_AMOUNT = 500_000') && files.worker.includes('moderationRewardThreshold') && files.app.includes('세금계산서·현금영수증·지출증빙이 발행되지 않습니다')],
  ['모바일 모달 안전영역', files.css.includes('.modal-header, .modal-head') && files.css.includes('flex: 1 1 auto') && files.css.includes('env(safe-area-inset-bottom)')],
  ['초기화 API 단일화', files.worker.includes("path === '/api/bootstrap'") && files.worker.includes('publicBootstrap') && files.client.includes("bootstrap: () => api('/api/bootstrap')") && files.app.includes('loadBootstrapData')],
  ['취소 미션 공개 제외', files.worker.includes("c.status NOT IN ('DRAFT', 'CANCELLED', 'REJECTED')")],
  ['공개 응답 캐시 최적화', files.worker.includes('stale-while-revalidate=30') && (await readFile(new URL('../public/_headers', import.meta.url), 'utf8')).includes('stale-while-revalidate=604800')],
  ['초소형 화면 단일열', files.css.includes('.challenge-meta { grid-template-columns: minmax(0, 1fr); }') && files.css.includes('.profile-stat-grid, .trust-factor-grid { grid-template-columns: minmax(0, 1fr); }')],
  ['Galaxy 브라우저 위로가기 겹침 방지', files.css.includes('.mobile-nav .mobile-create > span') && files.css.includes('margin-top: 0')],
  ['캐시 버전 일치', files.html.includes('styles.css?v=46') && files.html.includes('live-app.js?v=46') && files.app.includes("api-client.js?v=46") && (await readFile(new URL('../public/sw.js', import.meta.url), 'utf8')).includes("modu-challenge-v46") && (await readFile(new URL('../public/_headers', import.meta.url), 'utf8')).includes('/sw.js\n  Cache-Control: no-cache')],
  ['iPhone OAuth·계정찾기·취소 안정화', files.sw.includes("url.pathname.startsWith('/api/')") && files.app.includes('startSocialLogin') && files.app.includes('이메일 찾기') && files.app.includes('비밀번호 찾기') && files.app.includes("navigate('dashboard')")],
  ['웹앱 설치 안내', files.html.includes('app-install-banner') && files.app.includes('beforeinstallprompt') && files.app.includes('isIOSSafari')],
  ['CSS 괄호', (files.css.match(/{/g) || []).length === (files.css.match(/}/g) || []).length],
];

const failed = checks.filter(([, ok]) => !ok);
for (const [name, ok] of checks) console.log(`${ok ? 'PASS' : 'FAIL'} ${name}`);
if (failed.length) process.exit(1);
